package com.kids.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AiPromptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiPromptAllPropertiesEquals(AiPrompt expected, AiPrompt actual) {
        assertAiPromptAutoGeneratedPropertiesEquals(expected, actual);
        assertAiPromptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiPromptAllUpdatablePropertiesEquals(AiPrompt expected, AiPrompt actual) {
        assertAiPromptUpdatableFieldsEquals(expected, actual);
        assertAiPromptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiPromptAutoGeneratedPropertiesEquals(AiPrompt expected, AiPrompt actual) {
        assertThat(actual)
            .as("Verify AiPrompt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiPromptUpdatableFieldsEquals(AiPrompt expected, AiPrompt actual) {
        assertThat(actual)
            .as("Verify AiPrompt relevant properties")
            .satisfies(a -> assertThat(a.getStyleName()).as("check styleName").isEqualTo(expected.getStyleName()))
            .satisfies(a -> assertThat(a.getSystemPrompt()).as("check systemPrompt").isEqualTo(expected.getSystemPrompt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiPromptUpdatableRelationshipsEquals(AiPrompt expected, AiPrompt actual) {
        // empty method
    }
}
