package com.kids.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GeneratedStoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneratedStoryAllPropertiesEquals(GeneratedStory expected, GeneratedStory actual) {
        assertGeneratedStoryAutoGeneratedPropertiesEquals(expected, actual);
        assertGeneratedStoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneratedStoryAllUpdatablePropertiesEquals(GeneratedStory expected, GeneratedStory actual) {
        assertGeneratedStoryUpdatableFieldsEquals(expected, actual);
        assertGeneratedStoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneratedStoryAutoGeneratedPropertiesEquals(GeneratedStory expected, GeneratedStory actual) {
        assertThat(actual)
            .as("Verify GeneratedStory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneratedStoryUpdatableFieldsEquals(GeneratedStory expected, GeneratedStory actual) {
        assertThat(actual)
            .as("Verify GeneratedStory relevant properties")
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getAudioUrl()).as("check audioUrl").isEqualTo(expected.getAudioUrl()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeneratedStoryUpdatableRelationshipsEquals(GeneratedStory expected, GeneratedStory actual) {
        // empty method
    }
}
