package com.kids.learning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProgressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAllPropertiesEquals(Progress expected, Progress actual) {
        assertProgressAutoGeneratedPropertiesEquals(expected, actual);
        assertProgressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAllUpdatablePropertiesEquals(Progress expected, Progress actual) {
        assertProgressUpdatableFieldsEquals(expected, actual);
        assertProgressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressAutoGeneratedPropertiesEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressUpdatableFieldsEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress relevant properties")
            .satisfies(a -> assertThat(a.getStudentId()).as("check studentId").isEqualTo(expected.getStudentId()))
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressUpdatableRelationshipsEquals(Progress expected, Progress actual) {
        assertThat(actual)
            .as("Verify Progress relationships")
            .satisfies(a -> assertThat(a.getLesson()).as("check lesson").isEqualTo(expected.getLesson()));
    }
}
